env:
  browser: true
  node: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
rules:
  "import/extensions":
    - "ignorePackages"
  prettier/prettier: error
  "no-magic-numbers":
    - "error"
    - "ignore": [0, 1]
